// GENERATED by packages/cli/bin/x-codegen.ts — do not edit by hand.
import { config as admin } from '../../../admin/server'
import { config as user } from '../../../user/server'
const APPS = { admin, user } as const
export { APPS }
