LogFile /var/log/clamav/clamd.log
PidFile /run/clamav/clamd.pid
TemporaryDirectory /tmp
DatabaseDirectory /var/lib/clamav
LocalSocket /run/clamav/clamd.ctl
TCPSocket 3310
TCPAddr 0.0.0.0
MaxConnectionQueueLength 200
MaxThreads 12
ReadTimeout 180
SelfCheck 600
User clamav
ExitOnOOM yes
AlertExceedsMax yes
MaxScanSize 200M
MaxFileSize 100M
MaxRecursion 8
MaxFiles 1000
MaxScanTime 60000
StreamMaxLength 100M
